/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemFinanicalAdminWorkArea;

import System.EcoSystem;
import System.UserAccount.UserAccount;
import System.WorkRequest.*;
import System.WorkRequest.WorkRequest;
import UserInterface.BGPanel;
import UserInterface.MoneyPanel;
import java.awt.CardLayout;
import java.sql.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liufulai
 */
public class SystemFinanicalWorkArea extends MoneyPanel {

    /**
     * Creates new form SystemFinanicalWorkArea
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    UserAccount account;
    
    public SystemFinanicalWorkArea(JPanel userProcessContainer,UserAccount account, EcoSystem business) {
        this.userProcessContainer = userProcessContainer;
        this.business = business;
        this.account =account;
        initComponents();
        this.txtTotalRevenue.setText(String.valueOf(account.getPersonRevenue()));
        this.PopulateTable();
        labAccount1.setText(account.getUsername());
    }
    

   
    
    //The profit should in different percentage.
    public double GetEachProfit(WorkRequest wq){
        double profit = 0;
        if(wq instanceof EvaluateAPlayerRequest){
            profit += (wq.getTotalprice()*0.1);
        }
        else if(wq instanceof FindPlayerListRequest){
            profit += (wq.getTotalprice()*0.1);
        }
        else if(wq instanceof FreeTransferRequest){
            profit += (wq.getTotalprice()*0.1);
        }
        else if(wq instanceof LoanRequest){
            profit += (wq.getTotalprice()*0.1);
        }        
        else if(wq instanceof TransferRequest){
            profit += (wq.getTotalprice()*0.1);
        }
        return profit;
    }
    
    public void PopulateTable(){
        DefaultTableModel model = (DefaultTableModel) this.tblHistoryTransaction.getModel();
        model.setRowCount(0);        
        for (WorkRequest wq : this.account.getWorkQueue().getWorkRequestList()) {           
            if(wq.getStatus().equalsIgnoreCase("paid")){
                Object[] row = new Object[4];
                wq.setResolveDate(new Date(0));
                row[0] = String.valueOf(wq.getResolveDate());
                row[1] = wq.getWorkRequestType().getValue();
                row[2] = wq.getTotalprice();
                row[3] = this.GetEachProfit(wq);
                model.addRow(row);
            }           
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTotalRevenue = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistoryTransaction = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labAccount1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Muna", 1, 18)); // NOI18N
        jLabel1.setText("Total Revenue:");

        jLabel2.setFont(new java.awt.Font("Muna", 1, 18)); // NOI18N
        jLabel2.setText("System Finance");

        jLabel3.setFont(new java.awt.Font("Muna", 1, 18)); // NOI18N
        jLabel3.setText("History Transaction");

        txtTotalRevenue.setFont(new java.awt.Font("Muna", 1, 18)); // NOI18N
        txtTotalRevenue.setText("<>");

        tblHistoryTransaction.setAutoCreateRowSorter(true);
        tblHistoryTransaction.setForeground(new java.awt.Color(255, 255, 255));
        tblHistoryTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "EndDate", "Type", "Revenue", "Profit"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblHistoryTransaction);

        btnBack.setText("<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setText("UserAccount :");

        labAccount1.setText("<>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotalRevenue))
                            .addComponent(btnBack)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(labAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labAccount1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTotalRevenue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labAccount1;
    private javax.swing.JTable tblHistoryTransaction;
    private javax.swing.JLabel txtTotalRevenue;
    // End of variables declaration//GEN-END:variables
}
