/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PlayerAgent;

import PDF.exportPDF;
import Socket.Client;
import System.EcoSystem;
import System.Enterprise.Club;
import System.Enterprise.Enterprise;
import System.Enterprise.EvaluatingCompany;
import System.Game.Game;
import System.Network.Network;
import System.Organization.Organization;
import System.Player.Player;
import System.Role.System.SystemFinancialAdmin;
import System.UserAccount.UserAccount;
import System.WorkRequest.EvaluateAPlayerRequest;
import System.WorkRequest.FindPlayerListRequest;
import System.WorkRequest.WorkRequest;
import UserInterface.AgentPanel;
import UserInterface.BGPanel;
import UserInterface.MainJFrame;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victor
 */
public class PlayerEvaluationJPanel extends AgentPanel {

    /**
     * Creates new form PlayerEvaluation
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private Network network;
    private Enterprise enterprise;  
    private Organization organization;
    private UserAccount account;
    public PlayerEvaluationJPanel(JPanel userProcessContainer, EcoSystem business, Network network, Enterprise enterprise, Organization organization, UserAccount account) {
    
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;
        this.business = business;
        this.account =account;
        initComponents();
        ShowInfo();
        ShowTable();
        Configcbo();
        
    }
     public void ShowInfo(){
        labNetwork.setText(network.getName());
        labEnterprise.setText(enterprise.getName());
        labOrganization.setText(this.organization.getName());
        labUserAccount.setText(account.getUsername());
    }
  
     
     public void Configcbo(){    
        cboNetwork.removeAllItems();
        cboPlayer.removeAllItems();
        for(Network n :business.getNetworkList()){
            cboNetwork.addItem(n);
        }
        
    }
     
     
    
    public void ShowTable(){
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest wr :account.getWorkQueue().getWorkRequestList()){
           
            if(wr instanceof EvaluateAPlayerRequest||wr instanceof FindPlayerListRequest){
            Object[] row = new Object[3];
            row[0] = wr;
            row[1] = wr.getStatus();
            row[2] = wr.getTotalprice();
            
            model.addRow(row);
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labEnterprise = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labOrganization = new javax.swing.JLabel();
        labUserAccount = new javax.swing.JLabel();
        labNetwork = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboPlayer = new javax.swing.JComboBox();
        btnSend = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cboNetwork = new javax.swing.JComboBox();

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("NetWork:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("UserAccount:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Organization:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Enterprise:");

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Request Id", "Status", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblRequest);

        jLabel1.setText("Player:");

        cboPlayer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPlayerActionPerformed(evt);
            }
        });

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnPay.setText("Pay&Export");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel6.setText("Network:");

        cboNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNetwork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cboNetworkMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboNetworkMouseClicked(evt);
            }
        });
        cboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNetworkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addComponent(labNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(labEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(labOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(labUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSend))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnPay)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(labNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(labEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(labOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(labUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(cboPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed

        Network n = (Network)this.cboNetwork.getSelectedItem();
        boolean tag = false;
        for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){           
            if(e instanceof EvaluatingCompany){
                tag = true;
            }        
        }
        if(tag == false){
            JOptionPane.showMessageDialog(null, "The selected network doesn't have evaluation company");
            return;
        }
        
        Player p = (Player)this.cboPlayer.getSelectedItem();
        EvaluateAPlayerRequest wr = (EvaluateAPlayerRequest)this.account.getWorkQueue().CreateWorkRequest(WorkRequest.WorkRequestType.EvaluateAPlayerRequest);       
        wr.setSender(account);
        wr.setStatus("pending");
        wr.setPlayer(p);       
        for(Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()){           
            if(e instanceof EvaluatingCompany){
                e.getWorkQueue().getWorkRequestList().add(wr);
            }        
        }
        
        
        
        JOptionPane.showMessageDialog(null, "Evaluation request send success!");
        this.ShowTable();
        
        
       
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRequest.getSelectedRow();       
        if (selectedRow < 0){
             JOptionPane.showMessageDialog(null, "Please selete a Work request!");
            return;         
        }       
        WorkRequest work = (WorkRequest)tblRequest.getValueAt(selectedRow, 0);
        
        if(work instanceof EvaluateAPlayerRequest)
        {
            work.setStatus("Paid");
            double price = work.getTotalprice();
            // club contract need to reduce money
            
            // Evaluation enterprise need to add money
            account.setPersonRevenue(account.getPersonRevenue()+(int)work.getTotalprice());
            
            // system finiacial need to add money
            for(UserAccount ua : this.business.getUserAccountDirectory().getUserAccountList()){
                if(ua.getRole() instanceof SystemFinancialAdmin){
                    ua.getWorkQueue().getWorkRequestList().add(work);
                    int sysOldRevenue = (int)ua.getPersonRevenue();
                    int sysNewRevenue = (int)(sysOldRevenue+(price*0.1));
                    ua.setPersonRevenue(sysNewRevenue);
                    
                }
            }
            EvaluateAPlayerRequest eva = (EvaluateAPlayerRequest)work;
          
            String path=null;

         JFileChooser File= new JFileChooser();
         File.setFileSelectionMode(JFileChooser.FILES_ONLY);
         int i=File.showOpenDialog(null);
         if(i == File.APPROVE_OPTION){
             path=File.getSelectedFile().getAbsolutePath();
             String name=File.getSelectedFile().getName();            
             System.out.println("The path of current file"+path+"\nthe current file name"+name);
         }
         else{
             System.out.println("no File choosen");
         }
         System.out.println("Here is the eva"+((EvaluateAPlayerRequest) work).getReport());            
         exportPDF.fillAPlayerEvaluation((EvaluateAPlayerRequest)work, path);
        
             
        }
         ShowTable();
        if(work instanceof FindPlayerListRequest){
             work.setStatus("Paid");
             double price = work.getTotalprice();
            // club contract need to reduce money
            account.setPersonRevenue(account.getPersonRevenue()+(int)work.getTotalprice());
            // system finiacial need to add money
            for(UserAccount ua : this.business.getUserAccountDirectory().getUserAccountList()){
                if(ua.getRole() instanceof SystemFinancialAdmin){
                    ua.getWorkQueue().getWorkRequestList().add(work);
                    int sysOldRevenue = (int)ua.getPersonRevenue();
                    int sysNewRevenue = (int)(sysOldRevenue+(price*0.1));
                    ua.setPersonRevenue(sysNewRevenue);
                    
                }
            }
            FindPlayerListRequest eva = (FindPlayerListRequest)work;
            String path=null;

         JFileChooser File= new JFileChooser();
         File.setFileSelectionMode(JFileChooser.FILES_ONLY);
         int i=File.showOpenDialog(null);
         if(i == File.APPROVE_OPTION){
             path=File.getSelectedFile().getAbsolutePath();
             String name=File.getSelectedFile().getName();
             
             System.out.println("The path of current file"+path+"\nthe current file name"+name);}
         
             
         exportPDF.fillPlayersEvaluation((FindPlayerListRequest)work, path);
        
             
        }
       
        
        
         ShowTable();
        //export
       
    }//GEN-LAST:event_btnPayActionPerformed

    public void populateComboPlayer(){
        this.cboPlayer.removeAllItems();
        Network n = (Network)this.cboNetwork.getSelectedItem();
        //System.out.println("network:"+n.getName());
        for(Player p : n.getPlayerDirectory().getPlayerList()){
            //System.out.println("player:"+p.getName());
            
                this.cboPlayer.addItem(p);
            
        }
    }
    private void cboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNetworkActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNetworkActionPerformed

    private void cboPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboPlayerActionPerformed

    private void cboNetworkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboNetworkMouseClicked
        // TODO add your handling code here:
         populateComboPlayer();
    }//GEN-LAST:event_cboNetworkMouseClicked

    private void cboNetworkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboNetworkMousePressed
        // TODO add your handling code here:
        populateComboPlayer();
    }//GEN-LAST:event_cboNetworkMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnSend;
    private javax.swing.JComboBox cboNetwork;
    private javax.swing.JComboBox cboPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labEnterprise;
    private javax.swing.JLabel labNetwork;
    private javax.swing.JLabel labOrganization;
    private javax.swing.JLabel labUserAccount;
    private javax.swing.JTable tblRequest;
    // End of variables declaration//GEN-END:variables
}
