/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EvaluationReport;

import System.EcoSystem;
import System.Enterprise.Enterprise;
import System.Network.Network;
import System.Organization.Organization;
import System.UserAccount.UserAccount;
import UserInterface.ClubContract.ClubContracBlackboard;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author liufulai
 */
public class EvaReportWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form EvaReportWorkArea
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private Network network;
    private Enterprise enterprise;  
    private Organization organization;
    private UserAccount account;
    
    
    public EvaReportWorkArea(JPanel userProcessContainer, EcoSystem business, Network network, Enterprise enterprise, Organization organization, UserAccount account) {
    
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;
        this.business = business;
        this.account =account;
        initComponents();
        config1();
        config2();
    }
    
    public void config1(){
        CardLayout blackboardLayout = (CardLayout) blackBoradContainer.getLayout();
        ReporterWorkAreaJPanel panel = new ReporterWorkAreaJPanel(blackBoradContainer,business,network,enterprise,organization,account);
        blackBoradContainer.add("workArea",panel);
        blackboardLayout.next(this.blackBoradContainer);
    }
    
    public void config2(){
        CardLayout blackboardLayout = (CardLayout) myTransactionContainer.getLayout();
        ReporterChooseRequestJPanel panel = new ReporterChooseRequestJPanel(myTransactionContainer,business,network,enterprise,organization,account);
        panel.populateTable();
        myTransactionContainer.add("workArea",panel);
        blackboardLayout.next(this.myTransactionContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        blackBoradContainer = new javax.swing.JPanel();
        myTransactionContainer = new javax.swing.JPanel();

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });

        blackBoradContainer.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Black Board", blackBoradContainer);

        myTransactionContainer.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("My Transaction", myTransactionContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
      CardLayout blackboardLayout = (CardLayout) myTransactionContainer.getLayout();
        ReporterChooseRequestJPanel panel = new ReporterChooseRequestJPanel(myTransactionContainer,business,network,enterprise,organization,account);
        panel.populateTable();
        myTransactionContainer.add("workArea",panel);
        blackboardLayout.next(this.myTransactionContainer);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTabbedPane1MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel blackBoradContainer;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel myTransactionContainer;
    // End of variables declaration//GEN-END:variables
}
