/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EvaluationData;

import System.EcoSystem;
import System.Enterprise.Enterprise;
import System.Network.Network;
import System.Organization.Organization;
import System.UserAccount.UserAccount;
import UserInterface.ClubContract.ClubContracBlackboard;
import UserInterface.ClubContract.ClubContractTransactionJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author liufulai
 */
public class EvaDataWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form EvaDataWorkArea
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private Network network;
    private Enterprise enterprise;  
    private Organization organization;
    private UserAccount account;
    public EvaDataWorkArea(JPanel userProcessContainer, EcoSystem business, Network network, Enterprise enterprise, Organization organization, UserAccount account) {
    
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;
        this.business = business;
        this.account =account;
        initComponents();
        config1();
        config2();
    }
    
    public void config1(){
        CardLayout blackboardLayout = (CardLayout) gameContainer.getLayout();
        GameManagementJPanel panel = new GameManagementJPanel(gameContainer,business,network,enterprise,organization,account);
        gameContainer.add("workArea",panel);
        blackboardLayout.next(this.gameContainer);
    }
    
    public void config2(){
        CardLayout playerTransferLayout = (CardLayout) playerContainer.getLayout();
        PlayersInfoJPanel panel1 = new PlayersInfoJPanel(playerContainer,business,network,enterprise,organization,account);
        playerContainer.add("workArea",panel1);
        playerTransferLayout.next(this.playerContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        gameContainer = new javax.swing.JPanel();
        playerContainer = new javax.swing.JPanel();

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseEntered(evt);
            }
        });

        gameContainer.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Game Management", gameContainer);

        playerContainer.setLayout(new java.awt.CardLayout());
        jTabbedPane1.addTab("Player Information", playerContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseEntered

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        CardLayout playerTransferLayout = (CardLayout) playerContainer.getLayout();
        PlayersInfoJPanel panel1 = new PlayersInfoJPanel(playerContainer,business,network,enterprise,organization,account);
        playerContainer.add("workArea",panel1);
        playerTransferLayout.next(this.playerContainer);
    }//GEN-LAST:event_jTabbedPane1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gameContainer;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel playerContainer;
    // End of variables declaration//GEN-END:variables
}
