/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EvaluationData;

import Socket.Client;
import System.EcoSystem;
import System.Enterprise.Club;
import System.Enterprise.Enterprise;
import static System.Enterprise.Enterprise.EnterpriseType.EvaluatingCompany;
import System.Enterprise.EvaluatingCompany;
import System.Game.Game;
import System.Game.GameDirectory;
import System.Network.Network;
import System.Organization.Organization;
import System.Player.Player;
import System.UserAccount.UserAccount;
import UserInterface.BGPanel;
import UserInterface.EvaPanel;
import UserInterface.MainJFrame;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victor
 */
public class GameManagementJPanel extends EvaPanel {

    /**
     * Creates new form GameManagementJPanel
     */
    private JPanel userProcessContainer;
    private EvaluatingCompany enterprise;
    private Network network;
    private EcoSystem business;
    private Organization organization;
    private UserAccount account;
    public String path;

    GameManagementJPanel(JPanel userProcessContainer, EcoSystem business, Network network, Enterprise enterprise, Organization organization, UserAccount account) {
       
        this.userProcessContainer = userProcessContainer;
        this.enterprise = (EvaluatingCompany)enterprise;
        this.network = network;
        this.organization = organization;
        this.business = business;
        this.account =account;
        initComponents();
        ShowInfo();
        ShowTable();
        
    }
    
    public void ShowInfo(){
        labNetwork.setText(network.getName());
        labEnterprise.setText(enterprise.getName());
        labOrganization.setText(this.organization.getName());
        labUserAccount.setText(account.getUsername());
    }
    
    
    public void ShowTable(){
        DefaultTableModel model = (DefaultTableModel) tblGame.getModel();
        
        model.setRowCount(0);
        
        
       
        for (Game game : network.getGameDirectory().getGameList()){
            Object[] row = new Object[4];
            row[0] = game;
            row[1] = game.getGameTpye().getValue();
            row[2] = game.getHomeClub();
            row[3] = game.getGuestClub();
            
            model.addRow(row);
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labOrganization = new javax.swing.JLabel();
        labUserAccount = new javax.swing.JLabel();
        labNetwork = new javax.swing.JLabel();
        labEnterprise = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGame = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("NetWork:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("UserAccount:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Organization:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Enterprise:");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Game Management");

        tblGame.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Game Id", "Level", "Host Team", "Guest Team"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblGame);

        btnAdd.setText("Add&Update");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(48, 48, 48)
                        .addComponent(labNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(labEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addComponent(labUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(labNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(labEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(labOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(labUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        int selectedRow = tblGame.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Game game = (Game)tblGame.getValueAt(selectedRow, 0);
     
        OneGameInfoJPanel oneGameInfoJPanel = new OneGameInfoJPanel(userProcessContainer,game);
        userProcessContainer.add("oneGameInfoJPanel", oneGameInfoJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
                // TODO add your handling code here:
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
          path =null;
         JFileChooser gameFile= new JFileChooser();
         gameFile.setFileSelectionMode(JFileChooser.FILES_ONLY);
         int i=gameFile.showOpenDialog(null);
         if(i == gameFile.APPROVE_OPTION){
             path=gameFile.getSelectedFile().getAbsolutePath();
             String name=gameFile.getSelectedFile().getName();
             
             System.out.println("The path of current file"+path+"\nthe current file name"+name);}
         else{
         System.out.println("no File choosen");
              }

        // TODO add your handling code here:
        ReadGAME(path);

        ShowTable();
    }//GEN-LAST:event_btnAddActionPerformed
      
    public void ReadGAME(String path){
        File csv = new File(path);
        BufferedReader br = null;
        try{
            br = new BufferedReader(new FileReader(csv));
        }
        catch(FileNotFoundException e){
            e.printStackTrace();
        }
        String line = "";
        String everyLine = "";
        try{
            ArrayList<String> allString = new ArrayList<>();
                while((line = br.readLine())!= null){
                everyLine = line;
                allString.add(everyLine);
                String [] splitStr = everyLine.split(","); 
               
               Game g1=network.getGameDirectory().AddGame();
               
               int t =1;
               
               g1.setName(splitStr[0]);
               if(splitStr[1].equals("1")){
               g1.setGameTpye(Game.GameType.FinalMatch);
               t=4;
               }
               if(splitStr[1].equals("2")){
                   g1.setGameTpye(Game.GameType.KnockoutMatch);
                   t=3;
               }
               if(splitStr[1].equals("3")){
                   g1.setGameTpye(Game.GameType.Derbymatch);
                   t=2;
               }
               if(splitStr[1].equals("4")){
                   g1.setGameTpye(Game.GameType.LeagueMatch);
                   t=1;
               }
               for(Network n :business.getNetworkList()){
               for(Enterprise e :n.getEnterpriseDirectory().getEnterpriseList()){
                   
                   if(e.getName().equals(splitStr[2]))
                   {
                       g1.setHomeClub((Club)e);
                   }
               }}
               for(Network n: business.getNetworkList()){
               for(Enterprise e :n.getEnterpriseDirectory().getEnterpriseList()){
                   if(e.getName().equals(splitStr[3]))
                   {
                       g1.setGuestClub((Club)e);
                   }
                   
               }
               }
             //  if()
             
               g1.setHomeScore(Integer.parseInt(splitStr[4]));
               g1.setGusetScore(Integer.parseInt(splitStr[5]));
               g1.setHomePossession(Double.parseDouble(splitStr[6]));
               g1.setHomeShootNumber(Integer.parseInt(splitStr[7]));
               g1.setGuestShootNumber(Integer.parseInt(splitStr[8]));
               g1.setHomeOffSide(Integer.parseInt(splitStr[9]));
               g1.setGuestOffSide(Integer.parseInt(splitStr[10]));
               
              
               
               g1.getHomePlayerScore().add(splitStr[11]);
               g1.getHomePlayerScore().add(splitStr[12]);
               g1.getHomePlayerScore().add(splitStr[13]);
               g1.getHomePlayerScore().add(splitStr[14]);
               g1.getHomePlayerScore().add(splitStr[15]);
               g1.getHomePlayerScore().add(splitStr[16]);
               g1.getHomePlayerScore().add(splitStr[17]);
               g1.getHomePlayerScore().add(splitStr[18]);
               g1.getHomePlayerScore().add(splitStr[19]);
               g1.getHomePlayerScore().add(splitStr[20]);
               g1.getHomePlayerScore().add(splitStr[21]);
               
               g1.getGuestPlayerScore().add(splitStr[22]);
               g1.getGuestPlayerScore().add(splitStr[23]);
               g1.getGuestPlayerScore().add(splitStr[24]);
               g1.getGuestPlayerScore().add(splitStr[25]);
               g1.getGuestPlayerScore().add(splitStr[26]);
               g1.getGuestPlayerScore().add(splitStr[27]);
               g1.getGuestPlayerScore().add(splitStr[28]);
               g1.getGuestPlayerScore().add(splitStr[29]);
               g1.getGuestPlayerScore().add(splitStr[30]);
               g1.getGuestPlayerScore().add(splitStr[31]);
               g1.getGuestPlayerScore().add(splitStr[32]);
               

               
               Club clubh = null;
               for(Network nw:EcoSystem.getInstance().getNetworkList()){
                    for(Enterprise ep :nw.getEnterpriseDirectory().getEnterpriseList()){
                        if(ep.getName().equals(g1.getHomeClub().getName()))
                        { 
                             clubh =(Club) ep;
                             int i=-1;
                             for(Player p :clubh.getPlayerDirectory().getPlayerList()){
                                 
                                 i++;
                                 p.setGameNumber(p.getGameNumber()+1);
                                 p.setAllGameScore(p.getAllGameScore()+t*Double.parseDouble(g1.getHomePlayerScore().get(i)));
                                 

                             }
                             
                        }
                    }
                }
               
                Club clubg = null;
               for(Network nw:EcoSystem.getInstance().getNetworkList()){
                    for(Enterprise ep :nw.getEnterpriseDirectory().getEnterpriseList()){
                        if(ep.getName().equals(g1.getHomeClub().getName()))
                        { 
                             clubg =(Club) ep;
                             int i=-1;
                             for(Player p :clubg.getPlayerDirectory().getPlayerList()){
                                 
                                 i++;
                                 p.setGameNumber(p.getGameNumber()+1);
                                 p.setAllGameScore(p.getAllGameScore()+t*Double.parseDouble(g1.getGuestPlayerScore().get(i)));
                                 

                             }
                             
                        }
                    }
                }
               
              
               
               /*for(Seatcatalog c : a.getCatalog()){
                   if(c.getCatalognum().equals(splitStr[6])){
                       ap1.setSeatcatalog(c);
                   }  
               }*/

            }
         
        }
        catch(IOException e){
            e.printStackTrace();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labEnterprise;
    private javax.swing.JLabel labNetwork;
    private javax.swing.JLabel labOrganization;
    private javax.swing.JLabel labUserAccount;
    private javax.swing.JTable tblGame;
    // End of variables declaration//GEN-END:variables
}
